<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder {
    public function run(): void {
        DB::table('users')->insert([
            [
                'id'                    => 1,
                'username'              => 'super_admin',
                'name'                  => 'Super Admin',
                'email'                 => 'admin@admin.com',
                'email_verified_at'     => null,
                'password'              => Hash::make('12345678'),
                'terms_and_policy'      => false,
                'number'                => null,
                'website'               => null,
                'avatar'                => null,
                'about'                 => null,
                'country_id'            => null,
                'city_id'               => null,
                'state_id'              => null,
                'zip_code'              => null,
                'map_location'          => null,
                'address'               => null,
                'gender'                => null,
                'facebook_id'           => null,
                'google_id'             => null,
                'apple_id'              => null,
                'loyalty_point'         => null,
                'role'                  => 'admin',
                'status'                => 'active',
                'remember_token'        => null,
                'created_at'            => '2024-09-05 04:06:22',
                'updated_at'            => '2024-09-05 10:07:59',
            ],
            [
                'id'                    => 2,
                'username'              => 'villa_owner',
                'name'                  => 'Villa Owner',
                'email'                 => 'owner@owner.com',
                'email_verified_at'     => null,
                'password'              => Hash::make('12345678'),
                'terms_and_policy'      => false,
                'number'                => null,
                'website'               => null,
                'avatar'                => null,
                'about'                 => null,
                'country_id'            => null,
                'city_id'               => null,
                'state_id'              => null,
                'zip_code'              => null,
                'map_location'          => null,
                'address'               => null,
                'gender'                => null,
                'facebook_id'           => null,
                'google_id'             => null,
                'apple_id'              => null,
                'loyalty_point'         => null,
                'role'                  => 'owner',
                'status'                => 'active',
                'remember_token'        => null,
                'created_at'            => '2024-09-05 04:06:22',
                'updated_at'            => '2024-09-05 10:07:59',
            ],
            [
                'id'                    => 3,
                'username'              => 'user',
                'name'                  => 'User',
                'email'                 => 'user@user.com',
                'email_verified_at'     => null,
                'password'              => Hash::make('12345678'),
                'terms_and_policy'      => 1,
                'number'                => null,
                'website'               => null,
                'avatar'                => null,
                'about'                 => null,
                'country_id'            => null,
                'city_id'               => null,
                'state_id'              => null,
                'zip_code'              => null,
                'map_location'          => null,
                'address'               => null,
                'gender'                => null,
                'facebook_id'           => null,
                'google_id'             => null,
                'apple_id'              => null,
                'loyalty_point'         => null,
                'role'                  => 'user',
                'status'                => 'active',
                'remember_token'        => null,
                'created_at'            => '2024-09-05 04:06:22',
                'updated_at'            => '2024-09-05 10:07:59',
            ],
        ]);
    }
}
